[?php if ($field->isPartial()): ?]
    [?php include_partial('<?php echo $this->getModuleName() ?>/'.$name, array('type' => 'filter', 'form' => $form, 'attributes' => $attributes instanceof sfOutputEscaper ? $attributes->getRawValue() : $attributes)) ?]
[?php elseif ($field->isComponent()): ?]
    [?php include_component('<?php echo $this->getModuleName() ?>', $name, array('type' => 'filter', 'form' => $form, 'attributes' => $attributes instanceof sfOutputEscaper ? $attributes->getRawValue() : $attributes)) ?]
[?php else: ?]
    [?php if($form[$name]->getWidget() instanceof sfWidgetFormInputCheckbox) : ?]
        [?php echo $form[$name]->renderError() ?]
        [?php echo $form[$name]->render($attributes instanceof sfOutputEscaper ? $attributes->getRawValue() : $attributes) ?]
        [?php echo $form[$name]->renderLabel($label) ?]
    [?php else : ?]
        [?php echo $form[$name]->renderError() ?]
        [?php echo $form[$name]->renderLabel($label) ?]
        [?php echo $form[$name]->render($attributes instanceof sfOutputEscaper ? $attributes->getRawValue() : $attributes) ?]
    [?php endif; ?]

    [?php if ($help || $help = $form[$name]->renderHelp()): ?]
        <div class="help">[?php echo __($help, array(), 'sf_admin') ?]</div>
    [?php endif; ?]
[?php endif; ?]
